"$schema" = 'https://starship.rs/config-schema.json'

# Don't print a new line at the start of the prompt
add_newline = false

format = '$all$aws$kubernetes$character'

[aws]
disabled = false
format = '[aws $profile]($style) '

[line_break]
disabled = true

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 1
truncate_to_repo = false

[package]
disabled = true

[python]
disabled = true

[nodejs]
symbol = "⬢ "
version_format = "v${major}"

[kubernetes]
disabled = false
format = '[($context)]($style) '
style = 'red bold'
detect_env_vars = ['AXELAR_K8S']

[[kubernetes.contexts]]
context_pattern = 'arn:aws:eks:us-east-2:\d+:cluster/mainnet-cluster'
context_alias = 'mainnet'

[[kubernetes.contexts]]
context_pattern = 'arn:aws:eks:us-east-2:\d+:cluster/testnet-cluster'
context_alias = 'testnet'

[[kubernetes.contexts]]
context_pattern = 'arn:aws:eks:us-east-2:\d+:cluster/devnet-cluster'
context_alias = 'devnet'

[directory.substitutions]
"~/dev/axelar/axelar-contract-deployments" = "acd"
"~/dev/axelar/axelar-amplifier" = "amp"
"~/dev/axelar/axelar-amplifier-solana" = "amp-sol"
"~/dev/axelar/axelar-amplifier-stellar" = "amp-stellar"
